#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely with sleep 2 in between each iteration
# It displays "I am invincible!!!" in between each iteration

trap 'echo "I am invincible!!!"' SIGTERM
while true; do
	echo "To infinity and beyond"
	sleep 2
done
