#!/usr/bin/env bash
# This script is displaying "Best School" 10 time but at the 9th will
# display "Hi"
i=1
while [ $i -le 10 ]; do
	echo "Best School"
	if [ $i -eq 9 ]; then
		echo "Hi"
	fi
	let i+=1
done
