#!/usr/bin/env bash
# This script is displaying 10 times of "Best School", but on nineth iteration it shows "Hi."

count=0
while [ $count -lt 10 ]; do
	if [ $count -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	count=$((count+1))
done
