#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes
h=0
min=60

while true; do

	if [ $((min % 60)) -eq 0 ]; then
		echo "Hour: $((h % 13))"
		let h+=1
	else
		echo $((min % 60))
	fi

	if [ $h -gt 12 ] && [ $((min % 60)) -eq 59 ]; then
		break
	fi

	let min+=1
done
